run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: elida
  misspell:
    locale: US

issues:
  exclude-rules:
    # Ignore long lines in tests
    - path: _test\.go
      linters:
        - lll
    # Ignore error returns in tests for deferred closes
    - path: _test\.go
      text: "Error return value of .*(Close|Remove)"
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 10
